<?php
/**
 * Created by PhpStorm.
 * User: walter
 * Date: 12/09/14
 * Time: 12.41
 */
?>

<?php $_maincategorylisting = $this->getCurrentCategory() ?>
<?php $_categories = $this->getCurrentChildCategories() ?>
<!--<h2><?php echo $this->__('Browse Products') ?> </h2>-->
<div class="subcat-listing"style="margin-top: -12px;">
    <ul>
        <? foreach ($_categories as $_category): ?>
            <? if ($_category->getIsActive()): ?>
                <?php $cur_category = Mage::getModel('catalog/category')->load($_category->getId()); ?>
                <?php $layer = Mage::getSingleton('catalog/layer'); ?>
                <?php $layer->setCurrentCategory($cur_category); ?>
                <? if ($_imageUrl = Mage::getBaseUrl('media').'catalog/category/'.$this->getCurrentCategory()->getThumbnail()): ?>
                    <li class="subcat-products" style="width: 364px">
                        <a href="<?php echo $this->getCategoryUrl($_category) ?>"
                           title="<?php echo $this->htmlEscape($_category->getName()) ?>"/>
                        <div class="subcat-products-description" style="background: url(<?php echo $_imageUrl ?>)">
                            <div class="description-container"  style="width: 364px">
                                <div class="description-text">
                                    <? if ($_description = $this->getCurrentCategory()->getDescription()): ?>
                                        <p class="category-description">
                                            <?php echo $_description ?>
                                        </p>
                                    <?php endif; ?>
                                </div>
                            </div>
                        </div>
                        <!--<h3><?php /*echo $this->htmlEscape($_category->getName()) */?></h3>-->
                    </li>
                <?php endif; ?>
            <?php endif; ?>
        <?php endforeach; ?>
    </ul>
</div>
